# Generated by Django 3.1.5 on 2021-01-20 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sellerapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('nama_depan', models.CharField(max_length=100)),
                ('nama_belakang', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('kontak', models.CharField(max_length=14)),
                ('link', models.URLField(blank=True, null=True)),
                ('jenis_ruangan', models.CharField(choices=[('Jenis Ruangan', 'Jenis Ruangan'), ('Kamar Tidur', 'Kamar Tidur'), ('Kamar Mandi', 'Kamar Mandi'), ('Dapur', 'Dapur'), ('Ruang Keluarga', 'Ruang Keluarga'), ('Taman', 'Taman'), ('Tangga', 'Tangga'), ('Ruang Makan', 'Ruang Makan'), ('Exterior', 'Exterior'), ('Ruang Belajar', 'Ruang Belajar'), ('Ruang Kerja', 'Ruang Kerja'), ('Perpustakaan', 'Perpustakaan'), ('Lainnya', 'Lainnya')], default='Jenis Ruangan', max_length=50)),
                ('lainnya', models.CharField(blank=True, max_length=1000, null=True)),
                ('services', models.CharField(choices=[('Kategori', 'Kategori'), ('Arsitek', 'Arsitek'), ('Design Interior', 'Design Interior'), ('Kontraktor', 'Kontraktor'), ('Design and Build', 'Design and Build')], default='Pilihan Service', max_length=50)),
                ('jumlah_budget', models.PositiveIntegerField(default=0)),
                ('alamat', models.CharField(max_length=500)),
                ('kota', models.CharField(max_length=50)),
                ('provinsi', models.CharField(choices=[('Aceh', 'Aceh'), ('Sumatra Utara', 'Sumatra Utara'), ('Sumatra Barat', 'Sumatra Barat'), ('Riau', 'Riau'), ('Kepulauan Riau', 'Kepulauan Riau'), ('Jambi\t', 'Jambi'), ('Bengkulu', 'Bengkulu'), ('Sumatra Selatan', ' Sumatra Selatan'), (' Kepulauan Bangka Belitung', ' Kepulauan Bangka Belitung'), ('Lampung', 'Lampung'), ('Banten', 'Banten'), ('Jawa Barat', 'Jawa Barat'), ('Jakarta', 'Jakarta'), ('Jawa Tengah', 'Jawa Tengah'), ('Yogyakarta', 'Yogyakarta'), ('Jawa Timur', 'Jawa Timur'), ('Bali', 'Bali'), ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'), ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'), ('Kalimantan Barat', 'Kalimantan Barat'), ('Kalimantan Selatan', 'Kalimantan Selatan'), ('Kalimantan Tengah', 'Kalimantan Tengah'), ('Kalimantan Timur', 'Kalimantan Timur'), ('Kalimantan Utara', 'Kalimantan Utara'), ('Gorontalo', 'Gorontalo'), ('Sulawesi Barat', 'Sulawesi Barat'), ('Sulawesi Selatan', 'Sulawesi Selatan'), ('Sulawesi Tengah', 'Sulawesi Tengah'), ('Sulawesi Tenggara', 'Sulawesi Tenggara'), ('Sulawesi Utara', 'Sulawesi Utara'), ('Maluku', 'Maluku'), ('Maluku Utara', 'Maluku Utara'), ('Papua Barat', 'Papua Barat'), ('Papua', 'Papua')], default='Aceh', max_length=50)),
                ('deskripsi', models.TextField()),
                ('status', models.CharField(choices=[('Dalam Antrian', 'Dalam Antrian'), ('Dalam Pengerjaan', 'Dalam Pengerjaan'), ('Menunggu Pembayaran', 'Menunggu Pembayaran'), ('Selesai', 'Selesai')], default='Dalam Antrian', max_length=30)),
                ('buat', models.DateField(auto_now=True)),
                ('tanggal_pengerjaan', models.DateField(blank=True, null=True)),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('files', models.ImageField(default='default.jpg', upload_to='upload/files/')),
                ('bukti', models.ImageField(blank=True, null=True, upload_to='upload/bukti/')),
                ('feedback', models.TextField(blank=True, null=True)),
                ('setujui', models.CharField(blank=True, choices=[('Beri Persetujuan', 'Beri Persetujuan'), ('Setuju', 'Setuju'), ('Tidak Setuju', 'Tidak Setuju')], default='', max_length=50, null=True)),
                ('revisi', models.TextField(blank=True, null=True)),
                ('kepuasan', models.CharField(blank=True, choices=[('Puas', 'Puas'), ('Tidak Puas', 'Tidak Puas')], default='Puas', max_length=30, null=True)),
                ('emp_id', models.IntegerField(default=sellerapp.models.Request.ids, editable=False, unique=True, verbose_name='Code')),
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='karyawanUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data - Permintaan',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('buat', models.DateField(auto_now_add=True)),
                ('kepuasan', models.CharField(choices=[('Puas', 'Puas'), ('Tidak Puas', 'Tidak Puas')], default='', max_length=30)),
                ('emp_id', models.IntegerField(default=sellerapp.models.Invoice.ids, editable=False, unique=True, verbose_name='Code')),
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False)),
                ('oleh', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='sellerapp.request')),
            ],
            options={
                'verbose_name_plural': 'Data - Invoice',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='upload/display/2021/01/20')),
                ('image_1', models.FileField(upload_to='upload/display/2021/01/20')),
                ('image_2', models.FileField(upload_to='upload/display/2021/01/20')),
                ('image_3', models.FileField(upload_to='upload/display/2021/01/20')),
                ('oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sellerapp.request')),
            ],
        ),
    ]
