# Generated by Django 3.1.5 on 2021-01-20 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0002_auto_20210120_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='nama_belakang',
        ),
        migrations.RemoveField(
            model_name='request',
            name='nama_depan',
        ),
    ]
